%YAML:1.0

#--------------------------------------------------------------------------------------------
# Camera Parameters. Adjust them!
#--------------------------------------------------------------------------------------------
CameraMat: !!opencv-matrix
  rows: 3
  cols: 3
  dt: d
  data: [1364.45, 0.0,      958.327,
         0.0,     1366.46,  535.074,
         0.0,     0.0,      1.0     ]

DistCoeffs: !!opencv-matrix
  rows: 5
  cols: 1
  dt: d
  data: [0.0958277, -0.198233, -0.000147133, -0.000430056, 0.000000]

Camera.width: 1920
Camera.height: 1080